### ISSUE TITLE
'type' object is not subscriptable

### ISSUE THREAD

**Issue by luys8611** [PetitPotiron/python-convertio#6]
I'm using Ubuntu 20.04 and python3.8.10
I've installed python convertio 1.1.1, but when I import convertio, it gives following error.

```
Traceback (most recent call last):
  File "/home/ubuntu/test/convert.py", line 5, in <module>
    import convertio
  File "/home/ubuntu/test/.env/lib/python3.8/site-packages/convertio/__init__.py", line 1, in <module>
    from .client import *
  File "/home/ubuntu/test/.env/lib/python3.8/site-packages/convertio/client.py", line 8, in <module>
    from convertio.types import ConversionPostDict, ConversionPostDictOptions, ConversionPostResult, ConversionStatusResult
  File "/home/ubuntu/test/.env/lib/python3.8/site-packages/convertio/types.py", line 29, in <module>
    class ConversionPostDictOptionsOcrSettings(TypedDict, total=False):
  File "/home/ubuntu/test/.env/lib/python3.8/site-packages/convertio/types.py", line 30, in ConversionPostDictOptionsOcrSettings
    langs: list[str]
TypeError: 'type' object is not subscriptable
```

Anyone can help on this issue?

**Comment by PetitPotiron** [comment]
Hello, it seems your Python version does not support the code. Try updating python.

**Comment by PetitPotiron** [comment]
You need python 3.9 to get this working. (see [3.9 whatsnew](https://docs.python.org/3/whatsnew/3.9.html#type-hinting-generics-in-standard-collections) for more information)
